name: status-translation

on:
  pull_request:
    branches:
      - gh-pages
    paths:
      - 'en/**'
      - 'de/**'
      - 'es/**'
      - 'fr/**'
      - 'it/**'
      - 'ja/**'
      - 'ko/**'
      - 'pt-br/**'
      - 'ru/**'
      - 'sk/**'
      - 'th/**'
      - 'tr/**'
      - 'uk/**'
      - 'uz/**'
      - 'zh-cn/**'
      - 'zh-tw/**'




jobs:
  verify-translation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: | 
          npm install
          npm run verify-translation
          
          #git checkout ${GITHUB_REF#refs/heads/}
          git config --global user.name "github-actions"
          git config --global user.email "carlosstenzel@hotmail.com"
          git add .
          git commit -m "generated"
          git push

          
